version: '3'

services:

  app:
    build: ./
    image: mean
    container_name: mean
    ports:
      - 80:4040
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo

  meanexpress:
    container_name: meanexpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: odmp
      #ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: meanmongo
    image: mongo:3.6
    ports:
      - 27017:27017
    expose:
      - 27017
